version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - "9100:9100"
    - "5601:5601"
    volumes:
    - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
    - resources_esnet

networks:
  resources_esnet:
    external: true