version: "3"

services:
  renderer:
    image: ubleipzig/generator:0.1.0
    container_name: generator
    restart: always
    ports:
      - "9090:9090"
    environment:
        GENERATOR_HOME: /etc/generator
    volumes:
      - ./cfg/de.ubleipzig.elastic.manifests.generator.cfg:/etc/generator/de.ubleipzig.elastic.manifests.generator.cfg
    networks:
      - resources_esnet

networks:
  resources_esnet:
    external: true